In [1]:
!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [2]:
s1 = pd.Series([23,24,25,12,'32'])
s1

0    23
1    24
2    25
3    12
4    32
dtype: object

In [5]:
s2 = pd.Series(
    [23,45,67,12,34],
    index=['a','b','c','d','e'])

s2

a    23
b    45
c    67
d    12
e    34
dtype: int64

In [6]:
s3 = pd.Series(
    [23,45,67,12,34],
    dtype='float'
)
s3

0    23.0
1    45.0
2    67.0
3    12.0
4    34.0
dtype: float64

In [7]:
s4 = pd.Series({
    'e':65,
    'f':43,
    'c':45
})
s4

e    65
f    43
c    45
dtype: int64

In [8]:
d1 = pd.DataFrame([43,54,65,76])
d1

    0
0  43
1  54
2  65
3  76

In [9]:
d2 = pd.DataFrame([
    [2,3,4],
    [4,5,6],
    [1,2,3]
])
d2

   0  1  2
0  2  3  4
1  4  5  6
2  1  2  3

In [10]:
d2=pd.DataFrame(s2) # converting dataframe into series
d2

    0
a  23
b  45
c  67
d  12
e  34

In [11]:
d3=pd.DataFrame(
    [[2,3,4],[4,5,6],[1,2,3]],
    columns=['a','b','c']
)
d3

   a  b  c
0  2  3  4
1  4  5  6
2  1  2  3

In [12]:
d3=pd.DataFrame(
    [[2,3,4],[4,5,6],[1,2,3]],
    columns=['a','b','c'],index=['x','y','z'])
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

In [13]:
d3=pd.DataFrame(
    [[2,3,4],[4,5,6],[1,2,3]],
    columns=['Maths','science','english'],index=['1','2','3'])
d3

   Maths  science  english
1      2        3        4
2      4        5        6
3      1        2        3

In [15]:
dic = [
 {'alex':1,'joe':2},
 {'ema':5,'dora':10,'alice':20},
 {'ema':5,'dora':10,'alice':20}
]
pd.DataFrame(dic,index=['a','b','c'])

   alex  joe  ema  dora  alice
a   1.0  2.0  NaN   NaN    NaN
b   NaN  NaN  5.0  10.0   20.0
c   NaN  NaN  5.0  10.0   20.0

In [20]:
d3

   Maths  science  english
1      2        3        4
2      4        5        6
3      1        2        3

In [32]:
d3

   Maths  science  english
1      2        3        4
2      4        5        6
3      1        2        3

In [36]:
d3.insert(
    1,
    'new1',[45,52,66])
d3

   Maths  new1  science  english
1      2    45        3        4
2      4    52        5        6
3      1    66        2        3

In [37]:
d ={'c':1,'new1':33,'e':22}
df11= d3._append(d,ignore_index='ture')
df11

   Maths  new1  science  english    c     e
0    2.0    45      3.0      4.0  NaN   NaN
1    4.0    52      5.0      6.0  NaN   NaN
2    1.0    66      2.0      3.0  NaN   NaN
3    NaN    33      NaN      NaN  1.0  22.0

In [38]:

import numpy as np
d4 = pd.DataFrame({'abc':np.random.randint(2,6,size=(10)),'bcd':np.random.randint(4,10,size=(10)),'cde':np.random.randint(3,10,size=(10))})
d4

   abc  bcd  cde
0    4    6    9
1    3    5    6
2    3    9    9
3    2    6    7
4    2    9    7
5    2    5    9
6    2    8    8
7    2    5    9
8    5    8    9
9    2    7    8

In [41]:
d4.head()

   abc  bcd  cde
0    4    6    9
1    3    5    6
2    3    9    9
3    2    6    7
4    2    9    7

In [42]:

d4.tail()

   abc  bcd  cde
5    2    5    9
6    2    8    8
7    2    5    9
8    5    8    9
9    2    7    8

In [44]:
# info About the Data
# The DataFrames object has a method called info(),that gives you more information about the data set.'''
d4.info()
d4.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     10 non-null     int64
 1   bcd     10 non-null     int64
 2   cde     10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

            abc        bcd        cde
count  10.00000  10.000000  10.000000
mean    2.70000   6.800000   8.100000
std     1.05935   1.619328   1.100505
min     2.00000   5.000000   6.000000
25%     2.00000   5.250000   7.250000
50%     2.00000   6.500000   8.500000
75%     3.00000   8.000000   9.000000
max     5.00000   9.000000   9.000000

In [45]:
d4

   abc  bcd  cde
0    4    6    9
1    3    5    6
2    3    9    9
3    2    6    7
4    2    9    7
5    2    5    9
6    2    8    8
7    2    5    9
8    5    8    9
9    2    7    8

In [46]:
d4.loc[4:9,['abc','cde']]

d4.loc[[3,4,7],['abc','cde']]

   abc  cde
3    2    7
4    2    7
7    2    9

In [47]:
d4.abc

0    4
1    3
2    3
3    2
4    2
5    2
6    2
7    2
8    5
9    2
Name: abc, dtype: int64

In [48]:
d4.abc.values # data frame . column .values

array([4, 3, 3, 2, 2, 2, 2, 2, 5, 2])

In [49]:
d4['sub'] = d4.abc.values - d4.cde.values - d4.bcd.values
d4

   abc  bcd  cde  sub
0    4    6    9  -11
1    3    5    6   -8
2    3    9    9  -15
3    2    6    7  -11
4    2    9    7  -14
5    2    5    9  -12
6    2    8    8  -14
7    2    5    9  -12
8    5    8    9  -12
9    2    7    8  -13

In [50]:
a = [['rk',102,15000],['rama',103,20000],['krishna',104,25000]]
dfl = pd.DataFrame(a,columns = ['name','id','salary'])
dfl

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000

In [51]:
y=dfl[dfl.salary>=20000]
print(y)
y[['id','salary']]

      name   id  salary
1     rama  103   20000
2  krishna  104   25000

    id  salary
1  103   20000
2  104   25000

In [54]:
dfl._append({'name' : 'aravind','id' : 105,'salary' : 30000},ignore_index=True)

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3  aravind  105   30000

In [55]:
dfl = dfl._append({'name' : np.nan,'id' : 105,'salary' : 30000},ignore_index = True)
dfl

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      NaN  105.0  30000.0

In [56]:
dfl.isnull()

    name     id  salary
0  False  False   False
1  False  False   False
2  False  False   False
3   True  False   False

In [57]:
print(dfl.isnull().sum())

name      1
id        0
salary    0
dtype: int64

In [58]:
dfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   id      4 non-null      float64
 2   salary  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.0+ bytes

In [59]:
dfl.dropna()

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0

In [60]:
dfl

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      NaN  105.0  30000.0

In [61]:
dfl.fillna(value = 'abc')

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      abc  105.0  30000.0

In [62]:
dfl

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3      NaN  105.0  30000.0

In [63]:
dfl.drop([2],axis=0,inplace=True)
dfl

   name     id   salary
0    rk  102.0  15000.0
1  rama  103.0  20000.0
3   NaN  105.0  30000.0

In [64]:
import pandas as pd
df = pd.DataFrame({'Animal' : ['Falcon', 'Falcon','Parrot', 'Parrot'],'Max Speed' : [380., 370., 24., 26.],'wind Speed' : [380., 370., 24., 26.]})
df

   Animal  Max Speed  wind Speed
0  Falcon      380.0       380.0
1  Falcon      370.0       370.0
2  Parrot       24.0        24.0
3  Parrot       26.0        26.0

In [65]:
df.groupby(['Animal']).mean()

        Max Speed  wind Speed
Animal
Falcon      375.0       375.0
Parrot       25.0        25.0

In [66]:
df.T

                 0       1       2       3
Animal      Falcon  Falcon  Parrot  Parrot
Max Speed    380.0   370.0    24.0    26.0
wind Speed   380.0   370.0    24.0    26.0

In [68]:
import pandas as pd

data = {'firstname': ['Arun', 'Jebu', 'Venkat', 'Rekha', 'Majid','Mohsin'],
        'lastname': ['Kumar', 'Jacob', 'Raghavan', 'Singh', 'Khan','Khan'],
        'employmenttype': ['Service', 'Business', 'Student', 'Service', 'Business','Business'],
        'country' :['India','USA','USA','Sweden','Australia','Germany']}


df = pd.DataFrame(data, columns = ['firstname','lastname','employmenttype','country'])

print(df)

  firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia
5    Mohsin      Khan       Business    Germany

In [69]:
df1 = pd.get_dummies(df['employmenttype'], dtype=int)
df2 = pd.get_dummies(df['country'], dtype=int)
print(df1)
print(df2)

   Business  Service  Student
0         0        1        0
1         1        0        0
2         0        0        1
3         0        1        0
4         1        0        0
5         1        0        0
   Australia  Germany  India  Sweden  USA
0          0        0      1       0    0
1          0        0      0       0    1
2          0        0      0       0    1
3          0        0      0       1    0
4          1        0      0       0    0
5          0        1      0       0    0

In [70]:
df

  firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia
5    Mohsin      Khan       Business    Germany

In [71]:
import pandas as pd
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [72]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [73]:
df = pd.concat([india_weather, us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [74]:
df = pd.concat([india_weather, us_weather], ignore_index=True)

df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [75]:
import pandas as pd
emp = {"Name": ["Parker", "Smith", "William", "Parker"],
"Age": [21, 32, 29, 21]}
info = pd.DataFrame(emp)
print(info)
print("--------------------")
info = info.drop_duplicates()
print(info)

      Name  Age
0   Parker   21
1    Smith   32
2  William   29
3   Parker   21
--------------------
      Name  Age
0   Parker   21
1    Smith   32
2  William   29

In [76]:
def calc_sum(kiran):
    return kiran+1
data = {
  "x": [50, 40, 30],
  "y": [300, 1112, 42]
}
df = pd.DataFrame(data)
print(df)
x = df.apply(calc_sum)
print(x)

    x     y
0  50   300
1  40  1112
2  30    42
    x     y
0  51   301
1  41  1113
2  31    43

In [77]:
import pandas as pd

# Create a sample DataFrame with a 'Gender' column
data = {
    'Name': ['John', 'Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Gender': ['Male', 'Female', 'Male', 'Male', 'Female', 'Female'],
    'Age': [23, 35, 45, 40, 28, 33],
    'group':["cse","ece","eee","cse","ece","ece"],
}

df1 = pd.DataFrame(data)

df1

      Name  Gender  Age group
0     John    Male   23   cse
1    Alice  Female   35   ece
2      Bob    Male   45   eee
3  Charlie    Male   40   cse
4    David  Female   28   ece
5      Eva  Female   33   ece

In [78]:
# Convert 'Gender' column to categorical data
d = pd.Categorical(df1['group'])

# Print the categorical data# Convert 'Gender' column to categorical data
d = pd.Categorical(df1['group'])

# Print the categorical data
print(d)

print(d)

['cse', 'ece', 'eee', 'cse', 'ece', 'ece']
Categories (3, object): ['cse', 'ece', 'eee']
['cse', 'ece', 'eee', 'cse', 'ece', 'ece']
Categories (3, object): ['cse', 'ece', 'eee']